baseURL = 'https://randomaccessvemuri.github.io/cybersec-blog/'
languageCode = 'en-us'
title = 'Writeups, Scripts, & Security Stuff'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Tanmay Vemuri"
  abstract = """
  I'm an offensive security enthusiast, currently pursuing OSCP and Security+, Student at Manipal Institute of Technology, Bangalore, India.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true

theme="HugoTeX"

customSCSS = ["scss/custom.scss"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
